### ISSUE TITLE
App keeps on shutting down

### ISSUE THREAD

**Issue by HB-Gwaay** [hashmesan/harmony-totp#67]
App shuts down on sending a token and adding a new custom token. It can not approve a transaction from a staking app as well.

**Comment by hashmesan** [comment]
Can you provide the token address you used , and the dapp you used? I'm seeing if it is token or app specific. Thanks!

**Comment by HB-Gwaay** [comment]
Hello there

The dapp I used is OneDAO and the token I tried to add is their native
token ODAO. I am using IOS version  Sef wallet. Sushiswap confirmation
messages for transactions  are also delaying a lot or not showing up at all.

**Comment by hashmesan** [comment]
I found the issue with the crash... the filter screen crash due to no logo image. We'll default them to a blank image for until it gets listed.   We'll bundle this fix in this week's release.   

As for the approval tx:   

I see the approve tx: https://explorer.harmony.one/tx/0x60b5986b6dcda38bd30159886d0814369141eeac409fdd73db1ffe13f93fedcd?activeTab=2  ;  It was successful.   Just try to reload the state, the app should see the previously approved tx.    

Sushiswap state doesnt work quite right on farm pages, but for swap it seems to work fine.  I'll report these findings to them. For now, you can close them a few seconds later, because the tx should be picked up.  See this video: https://sefwallet.gitbook.io/sef-wallet/sef-+-sushi-liquidity-mine

**Comment by HB-Gwaay** [comment]
Thank you for your email

See the screenshot below, the moment I click that funnel the app shuts down
automatically.

**Comment by hashmesan** [comment]
Correct, that "funnel" filter icon, is going to crash everytime until the new fix comes in. You can avoid it by delete the app & restore wallet... but adding custon token will still be broken until new fix :(

**Comment by HB-Gwaay** [comment]
Awesome, thanks!

**Comment by hashmesan** [comment]
1.0.3 is available on appstore. You will need to remove the previous added token by toggle it off, then add it again. Sending also is fixed. (provided you re-add it again)

**Comment by hashmesan** [comment]
If this is still an issue, please reopen this.
