### ISSUE TITLE
Different address appearing when you go to send transaction. Watch out

### ISSUE THREAD

**Issue by Minglesp** [hashmesan/harmony-totp#91]
I've had nothing but problems Since using this  wallet.  When I copied and pasted my harmony address after sending a different wallet was on the transaction and took my money

**Comment by hashmesan** [comment]
Are you sure it's not translating between eth and one address? The send box
allow for eth and confirm shows one address. Please copy and paste so i can
confirm too

**Comment by Minglesp** [comment]
one1gmeq9qvd4wq4sykyrcntmvzfyfaph8aqeq8pn7.  I can only see what is going into this wallet now on harmony explorer.  If i can see what is going out you will see a transaction to a address I did not send to. It had millions of dollars of harmony in the wallet

**Comment by Minglesp** [comment]
I think There is a hacker on your wallet that puts his address in on the transaction.  There is no way that I put a different address in. I copy and paste.

**Comment by hashmesan** [comment]
I think there is confusion because it's a vault address. The address one1gmeq9qvd4wq4sykyrcntmvzfyfaph8aqeq8pn7 is a smart address which I assume is your vault address.

These transactions are signed locally on the wallet and redirected to a relayer (one1gmeq9qvd4wq4sykyrcntmvzfyfaph8aqeq8pn7), which sends to the block chain on your behalf.  The transfer from contract will appear as "Internal transaction" which you have click inside to see. It won't show on the list page.
